version: 2
jobs:
  build:
    working_directory: ~/go/src/github.com/{USER}/{REPOSITORY_ROOT}
    docker:
      - image: cimg/go:1.19.0

    steps:
      - checkout:
          path: ~/go/src/github.com/{USER}/{REPOSITORY_ROOT}

      - run: mkdir bin
      - run: go get ./...
      - run: go test ./...
      - run: go build -o bin/blog.exe github.com/{USER}/{REPOSITORY_ROOT}/

      - store_artifacts:
          path: bin/
          destination: blog-app