# Golang CircleCI 2.0 configuration file
version: 2

orbs:
  heroku: circleci/heroku@1.0.0

jobs:
  build:
    docker:
      - image: cimg/go:1.19.0
    
    machine: true
    working_directory: /go/src/github.com/ezzycreative1/svc-blog-profile
    steps:
      - checkout
      - run: go get -v ./...
      - run: go test -v ./...

  deploy:
      docker:
        - image: buildpack-deps:trusty
      steps:
        - checkout
        - run:
            name: Deploy Master to Heroku
            command: |
              git push https://heroku:$HEROKU_KEY@git.heroku.com/svc-blog-profile.git master
    
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:  
          requires:
            - build
          filters:
            branches:
              only: main
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: go test -v

